### ISSUE TITLE
How dare you

### ISSUE THREAD

**Issue by zslabs** [gka/schnack#23]
😜

<img width="247" alt="screen shot 2017-10-20 at 2 10 36 pm" src="https://user-images.githubusercontent.com/1018402/31835662-780cbf36-b5a0-11e7-9efc-888a91d987ab.png">

Cool idea! Will be following this one.

**Comment by g-div** [comment]
Hey Zach, [here](https://www.vis4.net/blog/2017/10/hello-schnack/#comment-21) is someone you should should know!
