### ISSUE TITLE
Add indices to database

### ISSUE THREAD

**Issue by kannes** [gka/schnack#25]
I only took a quick look around and have no idea if maybe some of your modules automatically handles that, but if not: Add indices to the database for improved performance!

Generally simply add indices for terms used in WHERE clauses and ORDER BY clauses. It might include useless ones but the space waste on them will be neglectable.

From a quick look at https://github.com/gka/schnack/blob/master/src/db/queries.js I would suggest:

- comment.approved
- comment.created_at
- comment.id
- comment.rejected
- setting.name
- subscription.endpoint
- user.blocked
- user.id
- user.trusted

Of course it would be smarter even to use multi column indices depending on your actual WHERE clauses. :)

If you tell me where, I could add them to your SQL files.

**Comment by gka** [comment]
good idea. the best place to put them would be in `migrations/004-indices.sql`

the files follow this up/down syntax
```sql
-- Up
ALTER TABLE ADD INDEX...
-- Down
ALTER TABLE DROP INDEX...
```

**Comment by kannes** [comment]
Here you go: https://github.com/gka/schnack/pull/29
Untested!

**Comment by gka** [comment]
seems to be working!
