### ISSUE TITLE
Please be kind, containerize

### ISSUE THREAD

**Issue by jhabdas** [gka/schnack#28]
This is a cool project and I wish you much traction. And I wish for users much Docker.

**Comment by jhabdas** [comment]
![screen shot 2017-10-29 at 12 48 30 am](https://user-images.githubusercontent.com/440298/32136592-041267f2-bbd6-11e7-83a0-f74a8176ac26.png)

**Comment by g-div** [comment]
This is also on our roadmap. I'll add a Dockerfile soon.

This is just the beginning...
