### ISSUE TITLE
free hosting option for schnack?

### ISSUE THREAD

**Issue by janpio** [gka/schnack#35]
(Note that I have no real experience with node)

Is there a free hosting option for schnack, that supports adding a subdomain via CNAME to make it accessible?
Would Heroku work?

**Comment by gka** [comment]
good question. the tricky part is that (as of now) schnack is not using iframes, which is nice bc you can use your site CSS to style the comments etc, but the downside is that the schnack instance has to run on a subdomain under the same domain.

not sure if any free hoster would allow that.

I was thinking about adding in an iframe option to allow hosting on random domains. will open another ticket for that idea.

**Comment by janpio** [comment]
Sounds good.

My own research on free hosting where Schnack might possibly run:

- https://www.heroku.com/pricing#dynos, sleeps after 30min - without limit from $7
- https://www.openode.io/pricing, max 18h per day - super cheap entry plan per month at $0.18
- https://www.evennode.com/pricing, 2 processes only - might be enough? 10 processes from €6

(Couldn't figure out to install without Docker though, see #37)
