### ISSUE TITLE
How to install and test Schnack on localhost

### ISSUE THREAD

**Issue by janpio** [gka/schnack#37]
After I found out how to install and run schnack in #36, I tried to integrate it into my local Jekyll site running on http://127.0.0.1:4000/:

1. I paste the minimal code from the README:
```
<div class="comments-go-here"></div>
<script src="//comments.yoursite.com/embed.js"
    data-schnack-slug="post-slug"
    data-schnack-target=".comments-go-here">
</script>
```
2. As I am running locally, I replace `comments.yoursite.com` with `localhost:3000`.
3. Opening `localhost:3000/embed.js` in the browser works, I get some JS 💯 
4. Opening  http://127.0.0.1:4000/ I get this though:
```
embed.js:199 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at embed.js:199
    at embed.js:371
    at embed.js:373
```
`script.src` seems to be `http://localhost:3000/embed.js` (note that it picked up the `http://` along the way) - strange, this looks like a pretty valid URL to me :/
5. Opening the Jekyll site via http://localhost:4000 (instead of 127.0.0.1) same result.
6. Switching embed code to include `http://` changes the error to a CORS one:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/comments/post-slug. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
This is caused by a 500 response to a OPTIONS request to http://localhost:3000/comments/post-slug, which Schnack server is not happy about:
```
Error: Not allowed by CORS
    at checkOrigin (/mnt/c/Projects/ionic.zone/schnack/src/helper.js:52:14)
    at /mnt/c/Projects/ionic.zone/schnack/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/mnt/c/Projects/ionic.zone/schnack/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/mnt/c/Projects/ionic.zone/schnack/node_modules/cors/lib/index.js:204:7)
    at Layer.handle [as handle_request] (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/index.js:317:13)
    at /mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/index.js:335:12)
    at next (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/middleware/init.js:40:5)
```

As I see there is only an unfinished branch that adds a whitelist, and I can't quickly change to real domains/subdomains locally, I have to stop here.

Hope this helps a bit to see where you could improve the experience a bit. 
Let me know if I missed anything obvious or there exists a workaround to get it working locally.

**Comment by g-div** [comment]
Did you define `http://localhost:3000` as `schnack_host` in your `config.json` file ?

**Comment by janpio** [comment]
Yes.

Last config:
- Jekyll run on http://localhost:4000/
- Schnack running on http://localhost:3000/
- `embed.js` can be loaded from http://localhost:3000/embed.js
- `OPTIONS` request to http://localhost:3000/comments/post-slug fails (that the browser is doing because of CORS)
- `GET` request to http://localhost:3000/comments/post-slug works and returns useful looking data

Added a console.log for `origin` in line 48 of src/helper.js:
- GET request that works is "origin undefined"
- OPTIONS request that fails is "origin http://localhost:4000"

Possible that Schnack doesn't like the ports?

**Comment by janpio** [comment]
Oh interest, the problem is in `getSchnackDomain()`. Will open an issue.

**Comment by g-div** [comment]
Good to know, we will work on this.

I know it sucks, but in the meanwhile you can use something like [ngrok](http://ngrok.com/) to tunnel port 4000:

```
ngrok http 4000
```

Then you will get a domain that you can place as `schnack_host` in the `config.json` file.
The advantage would also be that you can eventually configure and test OAuth with Twitter and Github.

**Comment by janpio** [comment]
With my new knowledge from #41 I could make it work: Just configure `schnack_host` as `sub.localhost` and the Origin-Check will get the correct `localhost` to compare.

Works, my Jekyll site is now showing
![image](https://user-images.githubusercontent.com/183673/34169310-3f138e78-e4e7-11e7-8416-e3b353dc6fe4.png)

**Comment by janpio** [comment]
Logging in via Twitter then doesn't work, but this is more or less expected. My guess would be that it tried to set the cookie for my faked domain `sub.localhost` (where it also redirects after the OAuth process) and gives me this nice error message:

```
Error: Failed to find request token in session
    at SessionStore.get (/mnt/c/Projects/ionic.zone/schnack/node_modules/passport-oauth1/lib/requesttoken/session.js:13:44)
    at Strategy.OAuthStrategy.authenticate (/mnt/c/Projects/ionic.zone/schnack/node_modules/passport-oauth1/lib/strategy.js:214:33)
    at Strategy.authenticate (/mnt/c/Projects/ionic.zone/schnack/node_modules/passport-twitter/lib/strategy.js:87:40)
    at attempt (/mnt/c/Projects/ionic.zone/schnack/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/mnt/c/Projects/ionic.zone/schnack/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/c/Projects/ionic.zone/schnack/node_modules/express/lib/router/index.js:281:22
```

**Comment by janpio** [comment]
Set it up with `local.host:4000` and `schnack.local.host:3000`. 
Twitter same error as above, for Github it works (with the modifications from #42).

**Comment by Nick-Gottschlich** [comment]
@janpio Can you explain to me what you mean when you said `Just configure schnack_host as sub.localhost and the Origin-Check will get the correct localhost to compare.`? Do I have to make a change in `config.json`?

I'm trying to set up schnack.js on my homepage (https://github.com/Nick-Gottschlich/ng-homepage-2) which uses https://github.com/gatsbyjs/gatsby . Just trying to start with getting a local version running in my development environment with little success so far 😅

**Comment by janpio** [comment]
In the config file is a `schnack_host` setting. When the main site runs on "localhost", I had to configure Schnack to "schnack_host=sub.localhost" so some code was happy and did run without crashing.

But my best local working version was with the `schnack_host` setting at "schnack.local.host:3000" while my website was running at "local.host:4000". Had to add both domains to my `hosts` file though so they mapped to 127.0.0.1.

Schnack isn't _really_ ready to be deployed locally I think...

**Comment by Nick-Gottschlich** [comment]
Ah so what I'm hearing here is that I should be trying to just get it live on my site as opposed to running it locally. I'll probably make another issue when I completely fail at doing that 👍

**Comment by janpio** [comment]
Yep, by working with paths and local domains you make your live harder than it should be, just putting it on a subdomain of your normal site should be simpler.

**Comment by g-div** [comment]
I've added [some lines](https://github.com/gka/schnack/commit/e724da9f9d8c14401417737801e00b3918295efa) to fix this problem. It is now possible to run the server on `localhost`.

I've also updated the README and an extensive documentation is coming. I will close this issue, but feel free to re-open it or to create another issue about a specific problem.

**Comment by georgedorn** [comment]
Does this mean that running schnack on the _same_ host as the blog, but under a different path, won't work?  e.g. my blog is at `myuser.mydomain.com/blog` and I've got an apache reverse proxy directive for the `/schnack` location to send that to `localhost:3000`.  Despite this, watching the network requests, it looks like `/comments` is baked into the path and `/snchack` never appears.

**Comment by George3d6** [comment]
In spite of the seeming fix I'm getting an error trying sutff out on local host: Error: Not allowed by CORS

Any ideas what I could do ? My current config is:
```
{
    "schnack_host": "http://localhost:3000",
    "page_url": "http://sub.localhost:3000/posts/%SLUG%",
... etc
```

But I also tried adding `sub.` before the first url and also into both urls and also into neither. Would be nice ot get an actual example config for running on localhost :)
