### ISSUE TITLE
Add `process.env.PORT` as possible source for port

### ISSUE THREAD

**Issue by janpio** [gka/schnack#45]
Some hosts prefer to give you a port via `process.env.PORT`. 
Would probably make sense to include this in `server.js`.

**Comment by gka** [comment]
we can add this as fallback in case no port is defined in the config.json.

**Comment by gka** [comment]
added in ca71c4f

**Comment by janpio** [comment]
Thanks.

Shouldn't it overwrite config.port though? If the server tells me which port it expects to have the program listening, this is probably the better choice than what I manually configured.
