### ISSUE TITLE
javascript: URLs not filtered out properly

### ISSUE THREAD

**Issue by ryan-copperleaf** [gka/schnack#49]
Posting it here because it’s not really a risk. One bypass:

```markdown
[foo][1]

  [1]: jav&#X61;script:alert(1)
```

The important thing is the uppercase `X`. Working:

![Screenshot of alert(1) in live comment](https://user-images.githubusercontent.com/22670137/34239272-192bc066-e5bb-11e7-8845-358e99db655d.png)

**Comment by gka** [comment]
from what I see this is still an open issue in [marked](https://github.com/chjj/marked/issues/925), but it seems the folks over there are finally on track to fix it. will give this a few more days, if nothing happens here we'll switch to a different markdown renderer.

**Comment by styfle** [comment]
See https://github.com/chjj/marked/pull/587#issuecomment-100055513

**Comment by Feder1co5oave** [comment]
This was fixed in #976

**Comment by g-div** [comment]
[Fixed](https://github.com/gka/schnack/commit/92791915f1ec9f9fff2565aeecacfe83653d331b), thanks!
