### ISSUE TITLE
add reply function

### ISSUE THREAD

**Issue by moklick** [gka/schnack#9]
people want to answer directly to comments.

**Comment by gka** [comment]
how deep do we want to go on this feature? 

* **nesting:** do we want hackernews style endless nesting? or just replies to first level comments? 
* **ux:** should the reply button open up a new comment form right under the comment I'm replying to?
* **render order:** I guess replies should show up next to the comment they are replying to. but right now our sort order is reverse chronological, so the reply would need to go above the comment? but that seems weird

**Comment by gka** [comment]
- [ ] add `reply_to` field to comment schema
- [ ] show reply button under all comments for signed in users
- [ ] open (copy of?) new comment form after clicking on reply button
- [ ] send comment with reply_to id
- [ ] render replies underneath the comment they reply to, in chronological order

**Comment by gka** [comment]
all done except the notification. will make this a new issue
